server:
  port: 9090

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/HotelBookingSystem
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka client config
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      bookingHotelLocationFacilitiesReviewServiceBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      bookingHotelLocationFacilitiesReviewServiceRetry:
        maxAttempts: 3
        waitDuration: 1000

  ratelimiter:
    instances:
      bookingHotelLocationFacilitiesReviewServiceRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s