server:
  port: 9094

spring:
  application:
    name: REVIEW-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/HotelBookingSystem
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka client config
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka